### ISSUE TITLE
Expert - search can produce strange results.

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#24]
### Actual behaviour
Search for Expert, Filters = name contains, Keywords = pieter (first name).
Resulting list is not sorted.
If search string is found in last name, it is also displayed.

![screen shot 2017-07-12 at 16 55 24](https://user-images.githubusercontent.com/30799556/29030538-a448e43e-7b8b-11e7-8f0f-18ae65adbd85.png)

### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by AdiKakodkar** [comment]
After speaking to mithun it appears that it was a request from Mark/Kristin in Oct 2016, to allow sorting by relevence. This is when the filter "Name contains" was asked to be made default.

So that the most relevent items appear at the top. i.e. if full name is searched then the expert with the full name is displayed at the top.

But, we need more info from Mithun

**Comment by MarkVanCrombrugge** [comment]
Problem solved by using a different search engine.
Mark only started looking into OE during May 2017.
